// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { GameserverBaseArgs } from "./gameserverBase";
export type GameserverBase = import("./gameserverBase").GameserverBase;
export const GameserverBase: typeof import("./gameserverBase").GameserverBase = null as any;
utilities.lazyLoad(exports, ["GameserverBase"], () => require("./gameserverBase"));

export { GameserverBaseListArgs } from "./gameserverBaseList";
export type GameserverBaseList = import("./gameserverBaseList").GameserverBaseList;
export const GameserverBaseList: typeof import("./gameserverBaseList").GameserverBaseList = null as any;
utilities.lazyLoad(exports, ["GameserverBaseList"], () => require("./gameserverBaseList"));

export { GameserverBasePatchArgs } from "./gameserverBasePatch";
export type GameserverBasePatch = import("./gameserverBasePatch").GameserverBasePatch;
export const GameserverBasePatch: typeof import("./gameserverBasePatch").GameserverBasePatch = null as any;
utilities.lazyLoad(exports, ["GameserverBasePatch"], () => require("./gameserverBasePatch"));

export { GameserverOverlayArgs } from "./gameserverOverlay";
export type GameserverOverlay = import("./gameserverOverlay").GameserverOverlay;
export const GameserverOverlay: typeof import("./gameserverOverlay").GameserverOverlay = null as any;
utilities.lazyLoad(exports, ["GameserverOverlay"], () => require("./gameserverOverlay"));

export { GameserverOverlayListArgs } from "./gameserverOverlayList";
export type GameserverOverlayList = import("./gameserverOverlayList").GameserverOverlayList;
export const GameserverOverlayList: typeof import("./gameserverOverlayList").GameserverOverlayList = null as any;
utilities.lazyLoad(exports, ["GameserverOverlayList"], () => require("./gameserverOverlayList"));

export { GameserverOverlayPatchArgs } from "./gameserverOverlayPatch";
export type GameserverOverlayPatch = import("./gameserverOverlayPatch").GameserverOverlayPatch;
export const GameserverOverlayPatch: typeof import("./gameserverOverlayPatch").GameserverOverlayPatch = null as any;
utilities.lazyLoad(exports, ["GameserverOverlayPatch"], () => require("./gameserverOverlayPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:pm8s.io/v1:GameserverBase":
                return new GameserverBase(name, <any>undefined, { urn })
            case "kubernetes:pm8s.io/v1:GameserverBaseList":
                return new GameserverBaseList(name, <any>undefined, { urn })
            case "kubernetes:pm8s.io/v1:GameserverBasePatch":
                return new GameserverBasePatch(name, <any>undefined, { urn })
            case "kubernetes:pm8s.io/v1:GameserverOverlay":
                return new GameserverOverlay(name, <any>undefined, { urn })
            case "kubernetes:pm8s.io/v1:GameserverOverlayList":
                return new GameserverOverlayList(name, <any>undefined, { urn })
            case "kubernetes:pm8s.io/v1:GameserverOverlayPatch":
                return new GameserverOverlayPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "pm8s.io/v1", _module)
